import jsPDF from "jspdf";
import autoTable from "jspdf-autotable"; // 🟢 FIXED IMPORT

/* ──────────────────────────────────────────────
   KIT MANIFEST PDF
────────────────────────────────────────────── */
export function generateKitPDF(kit) {
  if (!kit) return;
  const doc = new jsPDF();

  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42);
  doc.text("SNACKMASTER", 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("Automated Inventory Traceability System", 14, 28);

  doc.setFontSize(16);
  doc.setTextColor(14, 165, 233);
  doc.text("INVENTORY REFILL MANIFEST", 14, 40);

  doc.setFontSize(11);
  doc.setTextColor(51, 65, 85);
  
  const formatDate = (ts) => {
    if (!ts) return "N/A";
    const date = ts.seconds ? new Date(ts.seconds * 1000) : new Date(ts);
    return date.toLocaleString("en-IN", {
      dateStyle: "medium",
      timeStyle: "short"
    });
  };

  doc.text(`Manifest ID: ${kit.id}`, 14, 50);
  doc.text(`Date Prepared: ${formatDate(kit.createdAt)}`, 14, 56);
  doc.text(`Status: ${kit.status.toUpperCase()}`, 14, 62);

  doc.text(`Machine ID: ${kit.machineId}`, 120, 50);
  doc.text(`Refiller: ${kit.refillerEmail}`, 120, 56);
  doc.text(`Org ID: ${kit.orgId}`, 120, 62);

  const tableData = kit.products.map((p) => [
    p.slotId,
    p.name + (p.swapped ? " (Swapped)" : ""),
    p.requiredQty.toString(),
    "[   ]"
  ]);

  autoTable(doc, {
    startY: 70,
    head: [["Slot", "Product Item", "Qty", "Packed"]],
    body: tableData,
    theme: "grid",
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: 255,
      fontStyle: "bold"
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 10, cellPadding: 6 },
    columnStyles: {
      0: { fontStyle: "bold", halign: "center", cellWidth: 30 },
      2: {
        fontStyle: "bold",
        halign: "center",
        textColor: [22, 163, 74],
        cellWidth: 30
      },
      3: { halign: "center", cellWidth: 30 }
    }
  });

  const finalY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);

  doc.text("Authorized Signature: _______________________", 14, finalY);
  doc.text("Refiller Signature: _______________________", 120, finalY);

  doc.setFontSize(8);
  doc.text(
    `Generated by SnackMaster System on ${new Date().toLocaleString("en-IN")}`,
    14,
    finalY + 15
  );
  doc.text("Confidential & Traceable Artifact", 14, finalY + 20);

  doc.save(`Kit_Manifest_${kit.machineId}_${kit.id.slice(-6)}.pdf`);
}

/* ──────────────────────────────────────────────
   INVENTORY MOVEMENT PDF
────────────────────────────────────────────── */
export function generateMovementPDF(movement) {
  if (!movement) return;
  const doc = new jsPDF();

  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42);
  doc.text("SNACKMASTER", 14, 22);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("Automated Inventory Traceability System", 14, 28);

  doc.setFontSize(16);
  doc.setTextColor(14, 165, 233);
  doc.text("INVENTORY MOVEMENT RECEIPT", 14, 40);

  doc.setFontSize(11);
  doc.setTextColor(51, 65, 85);

  const formatDate = (ts) => {
    if (!ts) return "N/A";
    const date = ts.seconds ? new Date(ts.seconds * 1000) : new Date(ts);
    return date.toLocaleString("en-IN", {
      dateStyle: "medium",
      timeStyle: "short"
    });
  };

  doc.text(`Receipt ID: ${movement.id}`, 14, 50);
  doc.text(`Date: ${formatDate(movement.createdAt)}`, 14, 56);
  doc.text(`Movement Type: ${movement.type.replace("_", " ")}`, 14, 62);

  doc.text(`Performed By: ${movement.performedBy}`, 120, 50);
  doc.text(`Org ID: ${movement.orgId}`, 120, 56);
  if (movement.batchId)
    doc.text(`Batch ID: ${movement.batchId}`, 120, 62);

  const tableData = [[
    movement.productName,
    movement.quantity.toString(),
    movement.referenceId || "N/A",
    movement.remarks || movement.purpose || "N/A"
  ]];

  autoTable(doc, {
    startY: 70,
    head: [["Product Item", "Quantity", "Reference ID", "Remarks / Purpose"]],
    body: tableData,
    theme: "grid",
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: 255,
      fontStyle: "bold"
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 10, cellPadding: 6 }
  });

  const finalY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);

  doc.text("Authorized Signature: _______________________", 14, finalY);

  doc.setFontSize(8);
  doc.text(
    `Generated by SnackMaster System on ${new Date().toLocaleString("en-IN")}`,
    14,
    finalY + 15
  );
  doc.save(`Receipt_${movement.type}_${movement.id.slice(-6)}.pdf`);
}

/* ──────────────────────────────────────────────
   BULK REPORT PDF
────────────────────────────────────────────── */
export function generateBulkReportPDF(title, columns, dataRows, orgId) {
  const doc = new jsPDF();

  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42);
  doc.text("SNACKMASTER", 14, 22);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Org ID: ${orgId}`, 14, 28);

  doc.setFontSize(16);
  doc.setTextColor(14, 165, 233);
  doc.text(title.toUpperCase(), 14, 40);

  autoTable(doc, {
    startY: 50,
    head: [columns],
    body: dataRows,
    theme: "grid",
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: 255,
      fontStyle: "bold"
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 9, cellPadding: 4 }
  });

  const finalY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Generated by SnackMaster System on ${new Date().toLocaleString("en-IN")}`,
    14,
    finalY
  );

  const safeTitle = title.replace(/\s+/g, "_");
  doc.save(`${safeTitle}_Report.pdf`);
}

/* ──────────────────────────────────────────────
   🟢 NEW: MACHINE SLOT AUDIT PDF
────────────────────────────────────────────── */
export function generateMachineSlotPDF(machine, slots) {
  const doc = new jsPDF();

  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42);
  doc.text("SNACKMASTER", 14, 22);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Machine ID: ${machine.id}`, 14, 28);
  doc.text(`Location: ${machine.location || "N/A"}`, 14, 33);

  doc.setFontSize(16);
  doc.setTextColor(14, 165, 233);
  doc.text(
    `MACHINE SLOT CONFIGURATION - ${machine.name || "AUDIT"}`,
    14,
    45
  );

  const tableData = slots.map((s) => {
    const code =
      110 + (Number(s.tray) - 1) * 10 + Number(s.slot_number);
    return [
      String(code),
      s.product_name || "EMPTY",
      s.current_qty.toString(),
      s.capacity.toString(),
      `${Math.round((s.current_qty / s.capacity) * 100)}%`
    ];
  });

  autoTable(doc, {
    startY: 55,
    head: [["Slot Code", "Product Name", "Current Qty", "Capacity", "Fill %"]],
    body: tableData,
    theme: "grid",
    headStyles: { fillColor: [14, 165, 233], textColor: 255 },
    styles: { fontSize: 10 }
  });

  const finalY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    `Generated on ${new Date().toLocaleString("en-IN")}`,
    14,
    finalY
  );

  doc.save(`Machine_Audit_${machine.id}.pdf`);
}